### ISSUE TITLE
执行 app:nuwaJarBeforeDex* 的时候数组越界错误

### ISSUE THREAD

**Issue by lguipeng** [jasonross/NuwaGradle#6]
17:36:35.099 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
17:36:35.105 [ERROR] [org.gradle.BuildExceptionReporter]        at org.objectweb.asm.ClassReader.a(Unknown Source)
17:36:35.111 [ERROR] [org.gradle.BuildExceptionReporter]        at org.objectweb.asm.ClassReader.a(Unknown Source)
17:36:35.114 [ERROR] [org.gradle.BuildExceptionReporter]        at org.objectweb.asm.ClassReader.a(Unknown Source)
17:36:35.117 [ERROR] [org.gradle.BuildExceptionReporter]        at org.objectweb.asm.ClassReader.b(Unknown Source)
17:36:35.128 [ERROR] [org.gradle.BuildExceptionReporter]        at org.objectweb.asm.ClassReader.accept(Unknown Source)
17:36:35.132 [ERROR] [org.gradle.BuildExceptionReporter]        at org.objectweb.asm.ClassReader.accept(Unknown Source)
17:36:35.140 [ERROR] [org.gradle.BuildExceptionReporter]        at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
17:36:35.147 [ERROR] [org.gradle.BuildExceptionReporter]        at cn.jiajixin.nuwa.util.NuwaProcessor.referHackWhenInit(NuwaProcessor.groovy:82)
17:36:35.150 [ERROR] [org.gradle.BuildExceptionReporter]        at cn.jiajixin.nuwa.util.NuwaProcessor.processJar(NuwaProcessor.groovy:34)
17:36:35.158 [ERROR] [org.gradle.BuildExceptionReporter]        at cn.jiajixin.nuwa.util.NuwaProcessor$processJar.call(Unknown Source)
17:36:35.162 [ERROR] [org.gradle.BuildExceptionReporter]        at cn.jiajixin.nuwa.NuwaPlugin$_apply_closure1_closure2_closure10_closure13.doCall(NuwaPlugin.groovy:154)
17:36:35.166 [ERROR] [org.gradle.BuildExceptionReporter]        at cn.jiajixin.nuwa.NuwaPlugin$_apply_closure1_closure2_closure10.doCall(NuwaPlugin.groovy:151)
17:36:35.171 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
17:36:35.173 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
17:36:35.176 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
17:36:35.183 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
17:36:35.187 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
17:36:35.190 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
17:36:35.208 [ERROR] [org.gradle.BuildExceptionReporter]        ... 57 more
17:36:35.216 [ERROR] [org.gradle.BuildExceptionReporter]

**Comment by lguipeng** [comment]
应该是某个类在构造函数注入Hack时发生的错误，也没有在日志中看到是哪个类，规避的方法是使用includepackage 减少需要处理的类，希望寒江不钓同学知悉，把这个插件做的更好，有时间我在调式下看看究竟是哪个类

**Comment by lcy644** [comment]
我也遇到了这个问题，不知道作者有没有修复的计划。
